### ISSUE TITLE
package name

### ISSUE THREAD

**Issue by brunobritodev** [chesterm8/aws-api-auth-policy-typescript#1]
I really know that is a weird question / suggestion ... but let go ahead...

I was trying to find an implementation of auth-policy in typescript for 2 or 3 hours now. (Maybe I could be faster doing by myself) until find you.

I've done the search by github and google in this way:
custom authorizer typescript
lambda api gateway typescript

Words in this way.

My suggestion is: be more explicit at your package name, like: aws-api-auth-policy-typescript and in description do some kind of reference for custom authorizer.

Just a suggestion. You can close this issue.

And congratulations for it!

**Comment by chesterm8** [comment]
I am glad you found the code useful, and thanks for the feedback! I have updated the package name and description slightly, hopefully they people find it easier. 

Cheers
